### ISSUE TITLE
Some request

### ISSUE THREAD

**Issue by ArieLeo** [AlexanderVorobyov/simple-decal-mesh#1]
Hi Alexander,
just accidentally finding your mesh decal system, 
i think this is very nice system especially for projecting a simple mesh decal.
Got some request if you don't mind.
I know this is almost a year repo, but just in case you still fiddling with it.
1. Adjust the volume size via scaling directly, not via the volume size property
2. Automatically update the decal, Editor only of course, and might be better only auto update when the decal volume transform are changed

**Comment by AlexanderVorobyov** [comment]
This repository is deprecated and was created as draft. I'm not recommended use this work for any purpose. It will not maintained, but in next few month i'll begin work on brand new system.

Thank You for advice.
